### ISSUE TITLE
Yarn install broken on node 8 and 9 versions

### ISSUE THREAD

**Issue by hodrigohamalho** [jshmrtn/s2i-nodejs-nginx#2]
Cloning "https://github.com/hodrigohamalho/app.git" ...
--
  | Commit:	3af429bbad5de6a14465274513c252b30a4c1be0 (first commit)
  | Author:	Rodrigo Ramalho <hodrigohamalho@gmail.com>
  | Date:	Mon Apr 16 17:34:41 2018 -0300
  | ---> Installing application source...
  | ---> Installing stock NGINX configuration...
  | ---> Installing your NodeJS dependencies...
  | yarn install v1.5.1
  | error An unexpected error occurred: "EACCES: permission denied, scandir '/opt/app-root/src/.config/yarn/link'".
  | info If you think this is a bug, please open a bug report with the information provided in "/opt/app-root/src/yarn-error.log".
  | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
  | error: build error: non-zero (13) exit code from jshmrtn/s2i-nodejs-nginx@sha256:d2aa538f15d8db9b4b7420b602331676af19d176c3f313a4c7931e3d168b75b6

**Comment by jeremyzahner** [comment]
@hodrigohamalho Thanks for reporting. I will release a fixed version any minute now.

**Comment by jeremyzahner** [comment]
@hodrigohamalho Can you evaluate if the issues is resolved?
